sudo: false
language: php

php:
  - 7.0
  - 7.1
  - hhvm

env:
  - CONFIG=dev

before_script:
  - composer self-update
  - composer install --prefer-source

script: ./vendor/bin/phpunit --bootstrap=./test/bootstrap.php --coverage-text ./test/

cache:
  directories:
    - $HOME/.composer/cache
