sudo: false
language: php

php:
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - secure: "whXi8aGCbEPQeCIgvaBYaVGJGjBfHuYN4tX6z+Xf4JK6juG7VDsMgHs4HzqcxFHHUwxzo+zmhvuLykTrQ437w20N85GInlqrVj0hSwjJHhrVy2OfyIfwHKtzsF+4Z4NhByOhKvm2KIzlrdTUbukZt+dYxHJKv68nSS+rI0sbVdI6WGvBZ5ETJLEXXKsO2EVJWHELu7FYn+ephMoVPjP0JaF7DoUkrT3PS0QTZf9qvEF559hkjhOtNBt4O/HIIQWeLnwJTjyI7LR60gR8cHG3+F+aWi03oWpjw37ZQ2ZpRBiU/Wkljp99mbRpvs9vIB9CY65x6Vewtxvak4PC27sjV1LcfUEm3fuKWwzt4lZlsU/i4vwOJbq0VPVurQgJqSXEIH1ek3R8I6GT0DyjVEPPAaqalyB301vSuLJiFRWPQQfBHUtOR+Y7QZJFXnJcdGRhz3oek2M00Aii+PV0/EsUBRUMuzzT1P+RZr7+LIgMs1scLDeBuD1Umdiv3KZ9zVv07ITazMyGnBDcCij25y+70o0kespSCxv4pinIm/Th5QXiahz4MfU5Ayx3ZyXrLM0ZFe/ju8wUJQADzzR82CIkc9hlZN8/mXrM0Dzvm4TuYfvnQrgr4p7w+NUIkUDTIiaSToc1ZzCrGQuhrH8To4AgqeaNasJHMJVFdpYr8qyY5l8="
    - secure: "mBECrKgrphJI/ltq+8w2OgXDdL/BqWOyK/OscY8sBv+F1ytSVjn3jJq0gRe++yTAlU+j/dtnpFqqThygwtWrzWoAqJfT0AJOxxLaPVG3EIU2vBzslv6GrR81g6xRRqa9gtmPZ3C11Hrrf22YYHQg3JIlwOT9FyMb+rBFJODmJsSAKg4tAebjkt9HDACSM5WaTMzE7lucRy+IgkW1EikWzIeJFfGH5yZwaaiLjBWU0koMqkmPCNfhGB5R8qyMVmMXEGZoEZ0pNpbyICbYyTETgrK9fuOxpSZlmKoT1xUGWr7PY21qx+lZ3Fe+fs+78zfLvcrkLV9LtNV0VwShnuMJ6bbjaNgNNaJuR8U2m+wpHx++s7kp8murcHPmojYf7hdjBEAO4NWZcOzjKdAHCoPuD+eX+lmSWM8DCy/89d5qElQE1zeZS2XcAEg4QJMOlVGA9xWRsHQyVXHGrzn1SrXKTr1EP+JTMLytyCbzWmXQdgInacfWbS9U29i8lzYTc6sqAVzUnhrBm6W2xo9wLf0tqVRpysftU1q69IKZgMfOZ73BIIwxlXxgfjG/Q/MnJmBZisVYBVunao2nog3QkQGiCHBL3KZ1m2Un1lL7aw05crQOPfzFsug7WEgBCOhnVZDBbZVOrtxPKdG3OlViFgp07xLOQDiAgbaGCkSX4xc8NVw="
  matrix:
    - CONFIG=dev

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

before_install:
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"
  - composer remove --dev --no-update phpunit/phpunit
  - composer require doctrine/orm --no-update
  - composer require doctrine/migrations --no-update
  - composer require satooshi/php-coveralls --no-update
  - composer require codacy/coverage --no-update

install:
  - composer install --no-dev

after_script:
  - php vendor/bin/coveralls
  - php vendor/bin/codacycoverage clover report/coverage-clover/clover.xml
