sudo: false
language: php

php:
  - 7.0
  - 7.1

env:
  - CONFIG=dev

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+?$/

before_script:
  - composer require satooshi/php-coveralls --no-update --dev
  - composer install --prefer-source

after_script:
  - php vendor/bin/coveralls --coverage_clover report/coverage-clover/clover.xml
